{:user {:plugins      [[cider/cider-nrepl "0.15.0"]
                       [refactor-nrepl "2.4.0-SNAPSHOT"]
                       [lein-ancient "0.6.7"]
                       [lein-ring "0.9.6"]
                       [lein-environ "1.1.0"]
                       [lein-cljsbuild "1.1.0"]
                       [lein-kibit "0.1.3"]
                       [lein-repetition-hunter "0.1.0-SNAPSHOT"]
                       [jonase/eastwood "0.2.3"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.12"]
                       [repetition-hunter "1.0.0"]
                       [environ "1.1.0"]]
        :jvm-opts     ["-XX:MaxPermSize=200M"]}
 :env {:squiggly {:checkers                 [:eastwood :kibit]
                  :eastwood-exclude-linters [:unlimited-use]
                  :eastwood-options         { ;; :builtin-config-files ["myconfigfile.clj"]
                                             }}}}
